name: hutool:branch-1
on:
  push:
    branches:
    - branch-1
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [8]
        java-distribution: ['temurin']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java-distribution }}
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-maven
          path: $HOME/.m2
      - name: Script
        run: |
          export TZ=Asia/Shanghai
          mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip=true
      - name: Codecov
        if: ${{ success() }}
        run: bash <(curl -s https://codecov.io/bash)
